### ISSUE TITLE
Unable to scroll the table in iOS 7.x

### ISSUE THREAD

**Issue by naveenkumar-sourcebits** [shaps80/iMessageStyleReveal#6]
Hi,

When I include the files, my table view does;t scroll in iOS 7.x. I have a main table view and tapping on any item will go the another table view. The second table view is the place where I need to show the time stamp. It is working as expected but my first table view doesn't scroll.

I removed these added files and table view started working. Any idea what could be issue in iOS 7.x?

Thanks,

**Comment by shaps80** [comment]
this is fixed in my latest changes. I'll try an push these up this week. Thanks ;)

**Comment by naveenkumar-sourcebits** [comment]
Could you pls elaborate on what was the issue?

**Comment by shaps80** [comment]
quite simple and odd ;)

UITableView+SPXRevealAdditions.m -- line 64

Delete this line --  it isn't required. I originally thought I'd need to disable this but it turns out it causes your problem as well as another with pickerView's, etc...

self.panGestureRecognizer.enabled = NO;

I would have just done a quick update to the lib, but I'm in the process of adding a lot of new features, like separator support, backgroundView's, etc... so I'll update the lib later in the week. 

Let me know if this doesn't work for you ;)

**Comment by naveenkumar-sourcebits** [comment]
Ok thanks, I will check when I am free.
